---
YNDX:
  vars:
    ansible_user: liszt
    ansible_port: 22
    ansible_ssh_private_key_file: '{{ inventory_dir }}/group_vars/id_ed25519'
  hosts:
    db:
      ansible_host: 172.28.19.115
    nginx:
      ansible_host: 172.28.19.115
    php:
      ansible_host: 172.28.19.115
